project:
  type: website
  output-dir: docs

website:
  title: "Elizabeth Schultheis"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: www.linkedin.com/in/elizabeth-schultheis-938772203
format:
  html:
    theme: pulse
    css: styles.css

editor: visual

